services:
  api:
    container_name: express-tinyurl-api
    image: express-tinyurl-api
    build:
      dockerfile: express.dockerfile
    environment:
      - DB_URL='db'
      - NODE_ENV='production'
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}